#!/usr/bin/env python3
"""Load generated Codex output rows into Guandata forms through guancli."""

from __future__ import annotations

import argparse
import csv
import json
import subprocess
import time
from pathlib import Path
from typing import Any


FORM_CONFIG = {
    "门店诊断结果表": {
        "fm_id": "a_11770b-f0d7-4349-a33d-00d76e485ef2",
        "file": "门店诊断结果表.csv",
        "key": "诊断结果ID",
        "current_key": ["经销商代码", "统计月份"],
    },
    "官方排名分位结果表": {
        "fm_id": "a_50f89c-da7c-46cc-aaa1-b09a8de9b5b5",
        "file": "官方排名分位结果表.csv",
        "key": "排名结果ID",
        "current_key": ["经销商代码", "统计月份", "指标编码", "排名范围类型", "排名范围编码"],
    },
    "Codex批次状态表": {
        "fm_id": "a_1c81a3-b2b6-469d-adae-a4950184fa2f",
        "file": "Codex批次状态表.csv",
        "key": "批次状态ID",
        "current_key": ["经销商代码", "任务环节编码"],
    },
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_dir", help="Directory generated by run_mock_codex_diagnosis.py")
    parser.add_argument("--tables", nargs="*", choices=FORM_CONFIG.keys(), default=list(FORM_CONFIG.keys()))
    parser.add_argument("--limit", type=int, default=0, help="Limit rows per table; 0 means all rows")
    parser.add_argument("--mode", choices=["add", "upsert"], default="upsert", help="Write mode. upsert queries existing rows and updates exact key matches.")
    parser.add_argument(
        "--current-state-upsert",
        action="store_true",
        help="Update current-state rows by stable keys that do not include batch id. Official mode for scheduled jobs.",
    )
    parser.add_argument("--query-limit", type=int, default=5000, help="Rows to query from a form when --mode upsert")
    parser.add_argument(
        "--replace-dealer-current",
        action="store_true",
        help="Dangerous test-cleanup mode: delete existing dealer rows before writing. Do not use for scheduled jobs.",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print planned writes without calling guancli")
    parser.add_argument("--yes", action="store_true", help="Required for actual writes")
    return parser.parse_args()


def read_rows(path: Path) -> list[dict[str, Any]]:
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        return [normalize_row(row) for row in reader]


def normalize_row(row: dict[str, Any]) -> dict[str, Any]:
    cleaned: dict[str, Any] = {}
    for key, value in row.items():
        if value is None:
            cleaned[key] = ""
            continue
        text = str(value)
        if text == "":
            cleaned[key] = ""
        elif text.isdigit():
            cleaned[key] = int(text)
        else:
            try:
                cleaned[key] = float(text) if "." in text and text.replace(".", "", 1).isdigit() else text
            except ValueError:
                cleaned[key] = text
    return cleaned


def run_guancli_write(command: list[str], retries: int = 3) -> None:
    for attempt in range(1, retries + 1):
        result = subprocess.run(command)
        if result.returncode == 0:
            return
        if attempt == retries:
            raise subprocess.CalledProcessError(result.returncode, command)
        print(f"[retry] guancli write failed attempt={attempt}/{retries}; retrying")
        time.sleep(attempt * 2)


def form_add(fm_id: str, row: dict[str, Any]) -> None:
    payload = json.dumps(row, ensure_ascii=False)
    run_guancli_write(["guancli", "form", "add", fm_id, "--data", payload])


def form_update(fm_id: str, row_id: str, row: dict[str, Any]) -> None:
    payload = json.dumps(row, ensure_ascii=False)
    run_guancli_write(["guancli", "form", "update", fm_id, row_id, "--data", payload])


def form_delete(fm_id: str, row_id: str) -> None:
    run_guancli_write(["guancli", "form", "delete", fm_id, row_id])


def query_existing_records(fm_id: str, query_limit: int) -> list[dict[str, Any]]:
    command = ["guancli", "form", "query", fm_id, "--limit", str(query_limit), "-f", "json"]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise RuntimeError(
            "查询表单现有记录失败：\n"
            f"command={' '.join(command)}\n"
            f"stdout={result.stdout}\n"
            f"stderr={result.stderr}"
        )
    return json.loads(result.stdout or "[]")


def query_existing_index(fm_id: str, key_field: str, query_limit: int) -> dict[str, dict[str, Any]]:
    # 查询完整行以保留 rowId；--columns 会裁掉 rowId，无法执行 update。
    records = query_existing_records(fm_id, query_limit)
    index: dict[str, dict[str, Any]] = {}
    for record in records:
        key_value = record.get(key_field)
        row_id = record.get("rowId") or record.get("row_id")
        if key_value and row_id:
            index[str(key_value)] = record
    return index


def current_key_value(row: dict[str, Any], key_fields: list[str]) -> str:
    return "||".join(str(row.get(field, "")).strip() for field in key_fields)


def validate_current_keys(table_name: str, rows: list[dict[str, Any]], key_fields: list[str]) -> None:
    for row in rows:
        missing = [field for field in key_fields if str(row.get(field, "")).strip() == ""]
        if missing:
            raise RuntimeError(
                f"{table_name} 当前态主键字段不能为空：{','.join(missing)}；"
                f"业务主键={row.get('诊断结果ID') or row.get('排名结果ID') or row.get('批次状态ID')}"
            )


def query_current_state_index(fm_id: str, key_fields: list[str], query_limit: int) -> dict[str, dict[str, Any]]:
    records = query_existing_records(fm_id, query_limit)
    index: dict[str, dict[str, Any]] = {}
    for record in records:
        row_id = record.get("rowId") or record.get("row_id")
        if row_id:
            index[current_key_value(record, key_fields)] = record
    return index


def dealer_code_set(rows: list[dict[str, Any]]) -> set[str]:
    dealer_codes: set[str] = set()
    for row in rows:
        value = str(row.get("经销商代码", "")).strip()
        if not value:
            continue
        for code in value.split(","):
            code = code.strip()
            if code:
                dealer_codes.add(code)
    return dealer_codes


def record_matches_dealer(record: dict[str, Any], dealer_codes: set[str]) -> bool:
    value = str(record.get("经销商代码", "")).strip()
    if not value:
        return False
    record_codes = {code.strip() for code in value.split(",") if code.strip()}
    return bool(record_codes & dealer_codes)


def delete_existing_for_dealers(
    table_name: str,
    fm_id: str,
    key_field: str,
    dealer_codes: set[str],
    query_limit: int,
    dry_run: bool,
) -> int:
    if not dealer_codes:
        return 0
    records = query_existing_records(fm_id, query_limit)
    matches = [record for record in records if record_matches_dealer(record, dealer_codes)]
    for record in matches:
        row_id = record.get("rowId") or record.get("row_id")
        key_value = record.get(key_field, "")
        if not row_id:
            raise RuntimeError(f"{table_name} 匹配到旧记录但缺少 rowId：{key_value}")
        if dry_run:
            print(f"[dry-run] {table_name} delete-old {key_field}={key_value} rowId={row_id}")
        else:
            print(f"[delete-old] {table_name} {key_field}={key_value} rowId={row_id}")
            form_delete(fm_id, str(row_id))
    return len(matches)


def main() -> None:
    args = parse_args()
    run_dir = Path(args.run_dir)
    if not run_dir.exists():
        raise FileNotFoundError(run_dir)
    if not args.dry_run and not args.yes:
        raise SystemExit("实际写入请添加 --yes；建议先运行 --dry-run")
    if args.replace_dealer_current and args.limit:
        raise SystemExit("--replace-dealer-current 不能和 --limit 同时使用，避免删除全量旧记录后只写入部分新记录")
    if args.current_state_upsert and args.replace_dealer_current:
        raise SystemExit("--current-state-upsert 和 --replace-dealer-current 不能同时使用")

    summary = []
    for table_name in args.tables:
        config = FORM_CONFIG[table_name]
        rows = read_rows(run_dir / config["file"])
        if args.limit:
            rows = rows[: args.limit]
        dealer_codes = dealer_code_set(rows)
        deleted_count = 0
        if args.replace_dealer_current:
            deleted_count = delete_existing_for_dealers(
                table_name,
                config["fm_id"],
                config["key"],
                dealer_codes,
                args.query_limit,
                args.dry_run,
            )
        existing = {}
        current_key_fields = config.get("current_key", [])
        if args.current_state_upsert:
            validate_current_keys(table_name, rows, current_key_fields)
            existing = query_current_state_index(config["fm_id"], current_key_fields, args.query_limit)
        elif args.mode == "upsert" and not args.replace_dealer_current:
            existing = query_existing_index(config["fm_id"], config["key"], args.query_limit)
        add_count = 0
        update_count = 0
        skip_count = 0
        for row in rows:
            key_value = row.get(config["key"], "")
            lookup_key = current_key_value(row, current_key_fields) if args.current_state_upsert else str(key_value)
            existing_record = existing.get(lookup_key)
            row_id = ""
            if existing_record:
                row_id = str(existing_record.get("rowId") or existing_record.get("row_id") or "")
            if existing_record and str(existing_record.get(config["key"], "")) == str(key_value):
                skip_count += 1
                key_label = "current_key" if args.current_state_upsert else config["key"]
                print(f"[skip] {table_name} unchanged {key_label}={lookup_key}" + (f" rowId={row_id}" if row_id else ""))
                continue
            action = "update" if row_id else "add"
            if args.dry_run:
                key_label = "current_key" if args.current_state_upsert else config["key"]
                key_display = lookup_key if args.current_state_upsert else key_value
                print(f"[dry-run] {table_name} {action} {key_label}={key_display}" + (f" rowId={row_id}" if row_id else ""))
            else:
                key_label = "current_key" if args.current_state_upsert else config["key"]
                key_display = lookup_key if args.current_state_upsert else key_value
                print(f"[write] {table_name} {action} {key_label}={key_display}" + (f" rowId={row_id}" if row_id else ""))
                if row_id:
                    form_update(config["fm_id"], row_id, row)
                    update_count += 1
                else:
                    form_add(config["fm_id"], row)
                    add_count += 1
        if args.dry_run:
            add_count = sum(
                1
                for row in rows
                if (current_key_value(row, current_key_fields) if args.current_state_upsert else str(row.get(config["key"], ""))) not in existing
            )
            update_count = len(rows) - add_count
        summary.append(
            {
                "table": table_name,
                "rows": len(rows),
                "fm_id": config["fm_id"],
                "mode": args.mode,
                "current_state_upsert": args.current_state_upsert,
                "replace_dealer_current": args.replace_dealer_current,
                "deleted_old": deleted_count,
                "add": add_count,
                "update": update_count,
                "skip": skip_count,
            }
        )
    print(json.dumps({"run_dir": str(run_dir), "summary": summary, "dry_run": args.dry_run}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
